// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDyGKGMJ0tf5OG96pLHyiWbJWtuZj7Bc',
    appId: '1:835328413024:web:bd8516ffdd96cde71a6205',
    messagingSenderId: '835328413024',
    projectId: 'my-flutter-sign',
    authDomain: 'my-flutter-sign.firebaseapp.com',
    storageBucket: 'my-flutter-sign.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAALjAvNf511_jYtmdMdmmi1v-kntknMtE',
    appId: '1:835328413024:android:3c9e5ae3123a62ca1a6205',
    messagingSenderId: '835328413024',
    projectId: 'my-flutter-sign',
    storageBucket: 'my-flutter-sign.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJTZUQKQtX7vU5Dwxz6cRwDzxSGjEe1M',
    appId: '1:835328413024:ios:18d8fc26bf34f2341a6205',
    messagingSenderId: '835328413024',
    projectId: 'my-flutter-sign',
    storageBucket: 'my-flutter-sign.appspot.com',
    iosClientId: '835328413024-7tavglcnde45bp18m8ppemj8ebijglqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSign',
  );
}
